// <auto-generated />
namespace CuahangNongduoc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _2_AddSeed_FixUser_FixUserRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2_AddSeed_FixUser_FixUserRole));
        
        string IMigrationMetadata.Id
        {
            get { return "202510130852338_2_AddSeed_FixUser_FixUserRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
