// <auto-generated />
namespace CuahangNongduoc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _3_delete_user_session : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_3_delete_user_session));
        
        string IMigrationMetadata.Id
        {
            get { return "202510140508167_3_delete_user_session"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
